## Ninth Exercise

### Importing third-party libraries

In [1]:
!{sys.executable} -m pip install numpy
import numpy as np

You should consider upgrading via the 'C:\Users\stefan.kolev\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


### First Exercise

In [38]:
limits = (2, 10)
numbers = np.arange(3, 10)

print(np.logical_and(numbers > limits[0], numbers < limits[1]).all())

True


### Second Exercise

In [11]:
numbers = np.array([1, 5, 8, 18, 83])

print(not np.all(np.zeros(numbers)))

True


### Third Exercise

In [15]:
print(f'The array {numbers} has {numbers.size} elements with each element {numbers.itemsize} size in bytes, which means it has allocated {numbers.size * numbers.itemsize} bytes memory overall')
print(f'Another way to show it is by using nbytes: {numbers.nbytes} bytes allocated')

The array [ 1  5  8 18 83] has 5 elements with each element 4 size in bytes, which means it has allocated 20 bytes memory overall
Another way to show it is by using nbytes: 20 bytes allocated


### Fourth Exercise

In [17]:
numbers = np.arange(30, 71, 2)

print(numbers)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


### Fifth Exercise

In [18]:
identityMatrix = np.identity(3)

print(identityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Sixth Exercise

In [19]:
vector = np.zeros(10)
vector[5] = 11

print(vector)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


### Seventh Exercise

In [26]:
numbers = np.arange(1, 10)
numbers2 = np.arange(5, 15)

print(numbers)
print(numbers2)

print(np.intersect1d(numbers, numbers2))

[1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[5 6 7 8 9]


### Eighth Exercise

In [27]:
numbers = [1, 1, 1, 5, 38, 4, 4, 3]

print(np.unique(numbers))

[ 1  3  4  5 38]


### Ninth exercise

In [31]:
numbers = np.arange(1, 7).reshape((3, 2))

print(numbers)

[[1 2]
 [3 4]
 [5 6]]


### Tenth Exercise

In [32]:
print(np.diagflat(np.arange(4, 8)))

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]
